{{- if .Values.auth.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "definitely-not-crosswords.fullname" . }}-secrets
  labels:
    {{- include "definitely-not-crosswords.labels" . | nindent 4 }}
type: Opaque
data:
  KEYCLOAK_CLIENT_SECRET: {{ .Values.auth.clientSecret | b64enc | quote }}
  NEXTAUTH_SECRET: {{ .Values.auth.nextAuthSecret | b64enc | quote }}
  {{- if and (not .Values.database.cnpg.enabled) .Values.database.external.url }}
  DATABASE_URL: {{ .Values.database.external.url | b64enc | quote }}
  {{- end }}
{{- end }}
