{{- if .Values.observability.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "definitely-not-crosswords.fullname" . }}
  labels:
    {{- include "definitely-not-crosswords.labels" . | nindent 4 }}
    {{- with .Values.observability.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "definitely-not-crosswords.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: {{ .Values.observability.serviceMonitor.port | quote }}
      path: {{ .Values.observability.serviceMonitor.path | quote }}
      interval: {{ .Values.observability.serviceMonitor.interval | quote }}
{{- end -}}
